### ISSUE TITLE
/api/user需要一个用户专业的字段

### ISSUE THREAD

**Issue by Chronostasys** [Chronostasys/kshub#22]

**Comment by sanae555** [comment]
用户的专业还有班级，一个课程里面课设列表需要知道是哪个专业哪个班的哪个人上传的课设

**Comment by Chronostasys** [comment]
> 用户的专业还有班级，一个课程里面课设列表需要知道是哪个专业哪个班的哪个人上传的课设

这些我放课设的细节里返回，用户dto会增加CollegeId字段，对应学院id，你拿到学院id之后发请求可以请求到学院信息
